services:
  server:
    container_name: ${SERVER_HOST}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}
    depends_on:
      - db
    networks:
      - vue-net

  db:
    container_name: db
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - vue-net
  
  pg-db:
    container_name: pg-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
      # - ./pgdb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - vue-net

networks:
  vue-net:
    name: vue-net
    driver: bridge

volumes:
  dbdata:
  pgdata:
