services:
  server:
    container_name: ${SERVER_HOST}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}
    depends_on:
      - db
    networks:
      - vue-net

  db:
    container_name: ${DB_HOST}
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - ${HOST_DB_PORT}:${DB_PORT}
    networks:
      - vue-net

networks:
  vue-net:
    name: vue-net
    driver: bridge

volumes:
  dbdata:
